# Generated by Django 3.2.9 on 2023-12-04 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('part_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('part_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('part_note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('part_manufacturer_barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer Barcode')),
                ('part_manufacturer_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer Part Number')),
                ('part_oem_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='OEM Number')),
                ('part_qty_in_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity In Stock')),
                ('part_min_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Quantity')),
                ('part_compatible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Where to Use')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['part_name'],
            },
        ),
        migrations.CreateModel(
            name='PartsRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty_released', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity Released')),
                ('release_note', models.TextField(blank=True, null=True, verbose_name='Release Note')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partsrelease', to='parts.parts')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='PartsPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('po_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='PO Number')),
                ('invoice_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Invoice Number')),
                ('qty_ordered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity Ordered')),
                ('vendor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Name')),
                ('vendor_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Phone')),
                ('purchase_note', models.TextField(blank=True, null=True, verbose_name='Purchase Note')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partspurchase', to='parts.parts')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PartsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('partfile', models.FileField(upload_to='partsfiles/%Y/%m/%d/', validators=[parts.validators.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('part_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partsfile', to='parts.parts')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CompatibleMolds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mold_id', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2, null=True, verbose_name='Mold')),
                ('part_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moldparts', to='parts.parts')),
            ],
        ),
        migrations.CreateModel(
            name='CompatibleMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2, null=True, verbose_name='Machine')),
                ('part_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinparts', to='parts.parts')),
            ],
        ),
        migrations.CreateModel(
            name='PartsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2, null=True, verbose_name='Warehouse')),
                ('rack', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2, null=True, verbose_name='Rack')),
                ('bay', models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40')], max_length=2, null=True, verbose_name='Bay')),
                ('level', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2, null=True, verbose_name='Level')),
                ('position', models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40')], max_length=2, null=True, verbose_name='Position')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity In Stock')),
                ('part_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partslocation', to='parts.parts')),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaselocation', to='parts.partspurchase')),
            ],
            options={
                'unique_together': {('part_id', 'warehouse', 'rack', 'bay', 'level', 'position')},
            },
        ),
    ]
